---
python_transforms:
  - name: switch_check_transform
    class_name: Transform
    file_path: "switch_check/switch_check.py"
queries:
  - name: switch_check_query
    file_path: "switch_check/switch_check.gql"
artifact_definitions:
  - name: "Switch Check Results"
    artifact_name: "switch_check"
    parameters:
      name: "id"
    content_type: "text/plain"
    targets: "avd_leaf_switches"
    transformation: "switch_check_transform"