query {
  AvdLeafswitch {
    edges {
      node {
        id
        name {
          value
        }
        primary_address {
          node {
            address {
              value
            }
          }
        }
      }
    }
  }
}